{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "react.serviceAccountName" . }}
  labels:
{{ include "react.labels" . | indent 4 }}
{{- end -}}
